Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

ans:
    
    Yes, there is a difference in the data type of variables `list_` and `array_list`.

The variable `list_` is a regular Python list containing strings, whereas the variable `array_list` is a NumPy array created using `np.array()` with the same list of strings.

To print the data types of both variables, you can use the `type()` function. Here's the code:

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))
```

Output:

```
Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>
```

In the output, you can see that the data type of `list_` is `<class 'list'>`, indicating that it is a regular Python list, and the data type of `array_list` is `<class 'numpy.ndarray'>`, indicating that it is a NumPy array.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

ans:
    
    
    
    To print the data type of each element in both variables `list_` and `array_list`, you can use a loop to iterate through each element and apply the `type()` function to get the data type. Here's the code:

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in 'list_'
print("Data type of each element in 'list_':")
for item in list_:
    print(type(item))

# Print data type of each element in 'array_list'
print("\nData type of each element in 'array_list':")
for item in array_list:
    print(type(item))
```

Output:

```
Data type of each element in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
```

In the output, you can see that each element in `list_` has a data type of `<class 'str'>`, indicating that they are strings. Each element in `array_list` has a data type of `<class 'numpy.str_'>`, which is a NumPy-specific string data type. Note that NumPy arrays may use specialized data types for efficiency, and that's why the data type is shown as `<class 'numpy.str_'>` instead of the regular Python string data type.

Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

ans:
    
    
    
    Yes, there will be a difference in the data type of elements present in both variables `list_` and `array_list` after the change:

```python
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in 'list_'
print("Data type of each element in 'list_':")
for item in list_:
    print(type(item))

# Print data type of each element in 'array_list'
print("\nData type of each element in 'array_list':")
for item in array_list:
    print(type(item))
```

Output:

```
Data type of each element in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
```

In the output, you can see that the data type of each element in `list_` is `<class 'str'>`, indicating that they are strings, as before. However, the data type of each element in `array_list` is now `<class 'numpy.int64'>`, indicating that they are 64-bit integers. This is because we explicitly specified the `dtype` parameter as `int` when creating the NumPy array, causing the elements to be converted to integers.

Regarding the additional code you provided:

```python
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
```

This code creates a NumPy array `num_array` from a list of lists `num_list`. The elements in `num_list` are integers, and without specifying the `dtype` parameter, NumPy will automatically infer the data type as integers. Therefore, the data type of each element in `num_array` will be `<class 'numpy.int64'>`.

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

ans:
    
    
    
    To find the characteristics of the variable `num_array`, namely its shape and size, you can use the respective attributes of NumPy arrays. Here's the code:

```python
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of the array
array_shape = num_array.shape

# Find the size of the array
array_size = num_array.size

print("Shape of the array:", array_shape)
print("Size of the array:", array_size)
```

Output:

```
Shape of the array: (2, 3)
Size of the array: 6
```

In the output, you can see that the shape of the array is `(2, 3)`, indicating that it has 2 rows and 3 columns. The size of the array is `6`, which represents the total number of elements in the array.

The variable `num_array` is a 2-dimensional array created from the list of lists `num_list`. The `shape` attribute returns a tuple representing the dimensions of the array, and the `size` attribute returns the total number of elements in the array.

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

ans:
    
    
    You can create a NumPy array of a 3x3 matrix containing zeros only using the `numpy.zeros()` function. Here's the code:

```python
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)
```

Output:

```
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
```

In this code, the `numpy.zeros()` function creates a new array of the specified shape (3x3) and fills it with zeros. The resulting `zero_matrix` is a 3x3 NumPy array containing zeros only.